language: objective-c
os: osx
osx_image: xcode8.3

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    matrix:
      - MATRIX_TARGET="-sdk iphonesimulator8.1 -destination 'platform=iOS Simulator,name=iPhone 6'"
      - MATRIX_TARGET="-sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 6s'"
      - MATRIX_TARGET="-sdk iphonesimulator10.1 -destination 'platform=iOS Simulator,name=iPhone 7'"

script:
    - set -o pipefail
    - xcodebuild clean test -workspace FastEasyMapping.xcworkspace -scheme FastEasyMapping $MATRIX_TARGET -enableCodeCoverage YES | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash)
